version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/?authSource=admin

      - ME_CONFIG_BASICAUTH=false
    networks:
      - app-network
    depends_on:
      - mongodb

  myapp:
    build: .
    container_name: myapp
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on :
      - mongodb
    environment :
      - MONGO_URL=mongodb://admin:password@mongodb:27017/?authSource=admin

networks:
  app-network:
    driver: bridge
volumes:
  mongodb_data:
    driver: local
